#/bin/sh
# get current script directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# `zbobr.toml` - autogenerated config with default values
# `user.toml` - the specific user settings overriding the default config
$DIR/zbobr.sh -c $DIR/zbobr.toml -c $DIR/user.toml -c $DIR/proj.toml --logs $@
