#/bin/sh
# get current script directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# first parameter is the project directory, the rest are passed to zbobr.sh
PROJECT_DIR="$1"
shift
# show help message if project directory is not provided
if [ -z "$PROJECT_DIR" ]; then
    echo "Usage: $0 <project_directory> [zbobr_args...]"
    exit 1
fi
# validate project directory and make it absolute without changing directory
[ -d "$PROJECT_DIR" ] || { echo "Error: project directory does not exist: $PROJECT_DIR"; exit 1; }
[ "${PROJECT_DIR#/}" = "$PROJECT_DIR" ] && PROJECT_DIR="$PWD/$PROJECT_DIR"
# `zbobr.toml` - autogenerated config with default values
# `user.toml` - the specific user settings overriding the default config
# `<project>/zbobr.toml` - the project-specific overrides
./$DIR/zbobr.sh -c $DIR/zbobr.toml -c $DIR/user.toml -c $PROJECT_DIR/repo.toml --logs @$
    